name: realcicero
description: A multistreaming app for action cameras by Cicero
version: 1.0.0
# Created by Cicero

environment:
  sdk: '>=3.3.0 <4.0.0'  # Ajustado para compatibilidade com CI

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  webview_flutter: ^3.0.4  # Downgrade para compatibilidade com webview_flutter_plus
  flutter_vlc_player: ^7.1.4
  video_player: ^2.7.0
  ffmpeg_kit_flutter: ^6.0.3  # Substitui flutter_ffmpeg
  permission_handler: ^11.0.0  # Para gerenciar permissões
  shared_preferences: ^2.2.2   # Para salvar configurações
  webview_flutter_plus: ^0.3.0  # Para visualização avançada de webview (chat)
  flutter_inappwebview: ^5.7.2+3  # Alternativa para webview com mais recursos
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
