name: realcicero
description: A multistreaming app for action cameras by Cicero
version: 1.0.0
# Created by Cicero

environment:
  sdk: '>=3.22.0 <4.0.0' # Versão mais recente do Flutter em 2025

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  webview_flutter: ^4.5.0
  flutter_vlc_player: ^7.2.0 # Para streaming RTSP
  video_player: ^2.9.0 # Alternativa para vídeo, caso necessário

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
