name: realcicero
description: A multistreaming app for action cameras by Cicero
version: 1.0.0
# Created by Cicero

environment:
  sdk: '>=3.8.0 <3.9.0' # Compatível com Dart 3.8.1 (Flutter 3.8.x)

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0 # Versão compatível com Dart 3.8.x
  webview_flutter: ^4.4.2 # Versão compatível
  flutter_vlc_player: ^7.1.5 # Versão compatível
  video_player: ^2.8.0 # Versão compatível

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Versão compatível

flutter:
  uses-material-design: true
