name: realcicero
description: A multistreaming app for action cameras by Cicero
version: 1.0.0
# Created by Cicero

environment:
  sdk: '>=3.0.0 <4.0.0' # Atualizado para a versão mais recente compatível

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  webview_flutter: ^4.5.0
  flutter_vlc_player: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
